OrderN/CONQUEST-release

bin/README.md, src/Makefile, src/Makefile.Doc, src/io_module.f90, src/system.make, tools/BasisGeneration/Makefile, tools/BasisGeneration/makedeps, tools/BasisGeneration/system.make
Small tweaks to Makefiles and associated inputs
=> Fix missing file to allow compilation

tools/BasisGeneration/dimens_local_module.f90, tools/BasisGeneration/pseudo_tm_info.f90, tools/BasisGeneration/read_module.f90, tools/BasisGeneration/schro_module.f90, tools/BasisGeneration/write_module.f90
This change is for the issue #52.
=> F non integer atomic number gen basis

tools/BasisGeneration/radial_xc_LibXC_module.f90
=> Hot fix for XC bug with LibXC

src/force_module.f90, src/ion_electrostatic_module.f90, src/pseudo_tm_module.f90
This fixes issues with the non-neutral atom local HF force and the Ewald stress
=> Hot-fix for force and stress bugs

src/io_module.f90
Since the distance unit in xyz file is Angstrom, we expect the units of force and energy are eV/Angstrom and eV.
I feel sorry that the present units of force and energy are still Ha/Bohr and Ha. It is because the convert value of for_conv is 1.0 in default, then it will not change force unit when we use default units in Conquest_input.
Now, some local parameters of for_conv_loc, en_conv_loc, dist_conv_loc are used to
make all the units in this xyz file are with Angstrom (position) , eV (energy) and eV/Angstrom (force).
=> Unify the units in write_extxyz()

src/control.f90
The variable g0 was only defined on ionode on the first iteration
of lbfgs, and not on other processes.  This led to different search
directions and indexing errors (principally i_h2d).  The variable
is now defined on all processes.
This fixes issue #110 (discussed in #109 )
Bug reported by @lionelalexandre and root cause found by @negf
=> Correct error in lbfgs defining g0

docs/groundstate.rst, docs/input_tags.rst, docs/strucrelax.rst, src/H_matrix_module.f90, src/control.f90, src/force_module.f90, src/initial_read_module.f90, src/move_atoms.module.f90, src/pseudo_tm_info.f90
=> Improve structural optimisation

src/io_module.f90
Fractional when expecting Cartesian or vice versa
=> Add test for wrong kind of coordinates

tools/PostProcessing/read_module.f90
Only read band information for jobs where it's needed.  Fixes #136
=> Fix issue with charge post-processing

src/SelfCon_module.f90
Following work by Tsuyoshi, ensure that the total residual integrates to zero, but allow the G=0 term to vary during SCF cycle
Closes #81
=> Implement fix for Kerker and free spin

src/density_module.f90
For non-spin polarised charged cells, the electron number set in set_atomic_density was wrong (the density was scaled twice as the total number of electrons wasn't updated after scaling).  Now fixed.
=> Fix error in electron number for charged cells

src/energy_module.f90, src/force_module.f90, src/initial_read_module.f90, src/io_module.f90, src/minimise.f90
Output of potentials or wavefunctions were not compatible with the ASE output (resulted in an extra call to FindMinDM which overwrote the final_energy output to the ASE file).  Fixed this and tidied the ASE output a little (in particular changing io_close calls to close calls for safety).
=> Fix issue giving crash

src/control.f90
Debugged for the threshold in the cell optimisation (When AtomMove.OptCellMethod = 3).
=> Debugged for the threshold in the cell optimisation

README.md, docs/index.rst, docs/input_tags.rst, docs/strucrelax.rst, src/DiagModule.f90, src/SelfCon_module.f90, src/control.f90, src/energy_module.f90, src/force_module.f90, src/initial_read_module.f90, src/initialisation_module.f90, src/move_atoms.module.f90, src/pao_minimisation.module.f90
Update the develop branches with fixes found in release-1.1 branch
=> Bring changes from release-1.1 into develop

tools/PostProcessing/PostProcessCQ.f90, tools/PostProcessing/local_module.f90, tools/PostProcessing/output_module.f90, tools/PostProcessing/read_module.f90
Implemented basic XSF output (taken essentially verbatim from CONQUEST) and added spin moments as a possible output.
=> Implement XSF output

tools/PostProcessing/Makefile, tools/PostProcessing/ol_ang_coeff_subs.f90, tools/PostProcessing/process_module.f90, tools/PostProcessing/stm_module.f90
This should fix the problems with bands not integrating to one (also fixed a problem with wrapping grid points).
These are problems reported in issues #173 and #172
=> Bugfix post process charge

src/hartree.f90
Fixes issues identified in #162
=> Bugfix poor scf convergence

testsuite/README.md, testsuite/test_check_output.py
From discussion of #201. This PR allows you to pass a key to the precision function and return a different precision.
=> Add selecting custom precision by key

tools/PostProcessing/process_module.f90, tools/PostProcessing/read_module.f90
Changed band output so that defaults are now consistent. Removed unnecessary output when bands are not output.
=> Tidied defaults for band densities

src/ScalapackFormat.f90
For "Padding H and S matrices", changes needed in ScalapackFormat.f90 have been introduced.
The changed routines are
find_SC_row_atoms, find_ref_row_atoms, find_SC_col_atoms 
to have the extended tables for the padded parts.
=> Pull request for f-proj_PadHamiltonianMatrix

src/DiagModule.f90
A bug in the case where  Diag.KProcGroups > 1 has been removed. 
Size of w in gsum is also changed following the comment by Dave.
=> A bug in the case where  Diag.KProcGroups > 1 has been removed.

src/DiagModule.f90, src/ScalapackFormat.f90
A bug related to gsum is removed.
The part using "ceiling" has been also changed. (no effect)
=> A bug related to gsum is removed.

src/DiagModule.f90
Changed the size of 'w' from matrix_size_padH to matrix_size. 
-> This has removed the bug related to the inconsistency about the size of this array. 
In addition, the name of the array 'w' and 'local_w' were changed to 'evals' and 'local_evals', respectively.
=> Changed the size of 'w', and renamed 'w' and 'local_w'.

docs/index.rst, docs/references.bib, docs/theory_energy_force_stress.rst
This is background theory for the manual which will be expanded later.
=> Add documentation on energy, forces and stresses

src/ScalapackFormat.f90
A few conditions related to the number of processes, dimension of Hamiltonian Matrix and Block Size are now checked. At present, CONQUEST simply stops if inappropriate setting for the block size and MPI processes is given.
Main one is ..
proc_cols must be smaller than blocks_c = (matrix_size_padH/ block size)
=> Subroutine check_block_parameters was introduced.

tools/PostProcessing/read_module.f90
This is needed to correctly convert units for simulation cell and coordinates in io_module.f90 and wasn't set before.
=> Read distance units from input file

src/DMMinModule.f90, src/initial_read_module.f90, src/initialisation_module.f90, src/minimise.f90
There were various inconsistencies and issues with loading an existing density matrix which have been fixed; this should now be correct and efficient
=> Tidy up calls for restarting from existing density matrix

.github/workflows/makefile.yml, testsuite/run_conquest_tests.sh
Closes #254 
I set `OMP_STACKSIZE` to 100M as a first guess, let's see how that performs.
=> Set omp_stacksize in testsuite

docs/groundstate.rst, docs/input_tags.rst
Manual updates for Padding Hamiltonian
=> Manual updates for Padding Hamiltonian

src/io_module.f90
Closes https://github.com/OrderN/CONQUEST-release/issues/274
Modified the format of the forces in extXYZ output.
=> Change the format of the forces written in extXYZ output 

src/control.f90
Closes #315 
Correct definition of the change of temperature at each step in variable temperature MD simulations.
=> Corrected the expression for the temperature change rate (control.f90).

src/SelfCon_module.f90
As explained in issue #363 , matSatomf and matKatomf should be used instead of matS and matK
for MSSFs. 
MatSatomf and matKatomf can be used both for primitive PAOs and MSSFs.
=> Mulliken with MSSFs

src/store_matrix_module.f90
Subroutine write_Rij_MatrixElements is added to print out the distance Rij and matX_i,alpha,j,beta. I have not put the calling part yet, but
call write_Rij_MatrixElements('K',matK,Hrange,n_matrix=nspin,index=10)
will generate the file "Kmatrix_plot.i10.p000000". (You can omit "index=10", then the default value of index = 00)
=> Subroutine write_Rij_MatrixElements is added to store_matrix_module.f90

testsuite/test_003_bulk_BTO_polarisation/Ba.ion, testsuite/test_003_bulk_BTO_polarisation/O.ion, testsuite/test_003_bulk_BTO_polarisation/Ti.ion
This removes the issue of XC in this test (and creates identical results)
=> Changed XC code to Conquest PW91 from LibXC

tools/BasisGeneration/Makefile, tools/PostProcessing/Makefile
Changed PostProcessing and BasisGeneration to use the system.make file from src/system so only one is needed
=> Use one system.make file for all compilations

tools/BasisGeneration/read_module.f90, tools/BasisGeneration/write_module.f90
Also now output pseudopotential input file at the end of the HGH ion files
=> More output on type of pseudopotential added

src/initial_read_module.f90
With this version,
Default setting: Padding H = True
Padding H = true and Diag.BlockSizeR = Diag.BlockSizeC = 32
If users want to change the block size to check the efficiency, they should add one line
Diag.BlockSizeR INT
when PaddingH = False
the size of Hamiltonian is the # of matrix_size
Diag.BlockSieR and BlockSizeC are set as in the old version of Conquest.
(Even with the present version, the default value of Padding H = 'true', though Diag.BlockSizeR or C is not defined if they are not specified.)
=> Changed the default setting of Diag.BlockSizeR and C
