OrderN/CONQUEST-release

src/initial_read_module.f90, src/mult_module.f90
This comes from the CheckInitialAtomicDistances branch in the
old repository, but I've moved the test to be much earlier in
the initialisation (saving a lot of time).
I've also changed mult_module.f90 to be Unix formatted instead
of DOS formatted, so the diff looks much bigger than it should
be.
=> Implement test for atoms too close to each other

src/move_atoms.module.f90
The original version combined c/a and a/c into a single case,
which gave the wrong behaviour.  Now separated into individual
cases.
=> Bug fix: correct the  cell optimisation with constrained ratios

tools/BasisGeneration/read_module.f90
We now test for whether there are polarisation orbitals before
reading the flag; if there are not, then we set the default to
false, and abort if the user selects true.  This fixes a
cosmetic issue (where minimal basis functions were labelled
as polarisation though they weren't).
Closes #54
=> Change default for perturbative polarisation

src/ol_bessel_transforms.f90
The sin and cos FFTW calls in the new Bessel transforms
did not destroy the FFTW plans, leading to a signficant
memory leak.  The calls to destroy are now made.
=> Hotfix for memory leak in Bessel transforms

tools/BasisGeneration/radial_xc_LibXC_v2_module.f90, tools/BasisGeneration/radial_xc_LibXC_v3_module.f90, tools/BasisGeneration/radial_xc_LibXC_v4_module.f90
Bug fix for issue #63 caused by non-allocation of an array in `get_vxc` with LibXC
=> Bug fix for issue #63

src/biblio_module.f90
…io_assign" etc.
In "write_bib", I put "if(inode == ionode)" as the subroutine calls "io_assign" etc.
At present, all processes call io_assign, and try to write information to the file simultaneously, I think.
For debugging, it is also possible to call "write_bib" only from inode. 
(But, I thought it is safer to have if-clause here.)
=> A small bug in biblio_module

src/move_atoms.module.f90
When I moved the allocation part of `atom_vels` from `read_atomic_positions` to `init_md` following Dave's suggestion, I forgot that this array is used (in `update_pos_and_matrices`) even when `md` is not performed.  I now realized that we have to allocate this array  in `update_pos_and_matrices`, in the case of `cg`.
(At present, I assume we should not deallocate `atom_vels` in the subroutine, since this array is used many times during a job. But, if we need to reduce the memory size in other parts, we should deallocate it every time.)
=> Bugfix velocity ordering

tools/BasisGeneration/schro_module.f90
Debug: schro_module.f90 in tools/BasisGeneration
Polarization function is usually made from the last PAOs, but in some cases,
we want to generate polarization function from other PAOs.
(by setting Atom.PolarisedN ** and  Atom.PolarisedL **)
There was a bug in such cases.
=> debug: schro_module.f90 in tools/BasisGeneration for setting polarization

src/force_module.f90
The bug arose from calculating rsq from undefined variables
rx etc, instead of r(1) etc.  Fixed in two places in non-SC
force routine
=> Implement correct calculation of rsq

src/H_matrix_module.f90, src/SelfCon_module.f90, src/XC_CQ_module.f90, src/XC_LibXC_v4_module.f90, src/XC_LibXC_v5_module.f90, src/energy_module.f90, src/hartree.f90, src/initial_read_module.f90, src/minimise.f90, src/pao_minimisation.module.f90
Implement new subroutines to find the Hartree, XC and local pseudopotential/neutral atom energy from the output density so that the formal definition of DFT energy is calculated.  Also remove the check_DFT parameter.  Some tidying associated with unnecessary calls to `get_energy`.
=> Fix DFT energy

src/control.f90, src/initial_read_module.f90, src/io_module.f90, src/md_control_module.f90
The extended format type xyz file can attach information not only atomic positions, but also lattice vectors, energy, forces, etc.
The benefit of this format is that it can be recognized by Python Library ASE and very convenient to do machine learning with such data.
With ASE, it is easy to do further structure analysis or converting to other format of geometry, also preparation of Machine learning.
Add config_type (crystal_Si, liquid_Si, amorphous_Si, mono_vacancy_Si, etc.) to comment line from IO.Title with which people can easily separate or select the geometries in the same xyz file.
=> Create write_extxyz() for output a .xyz file with extended format

docs/input_tags.rst, src/control.f90, src/initial_read_module.f90
Implement a check on the unrestricted atom movement in SQNM so that the alpha parameter is not increased without limit.
=> Add limit to distance moved by atoms in SQNM

docs/input_tags.rst, src/H_matrix_module.f90, src/initial_read_module.f90, src/minimise.f90
The part to print out local potentials, such as Hartree, Pseudopotential, XC, Electrostatic, and total potentials has been changed. Now, we need at least one of `IO.DumpHarPot`, `IO.DumpXCPot`,  `IO.DumpPSPot`, `IO.DumpESPot` and `IO.DumpTotPot` need to be set `true`.  
It is valid only in "static" calculations and these files are printed out only once at the end of each job.
=> Revised the part to print out (local) potentials. (Hartree, Pseudopotential, XC, Electrostatic, and total)

src/initial_read_module.f90
Change input so that diagonalisation is selected unless the specific ordern keyword is given (avoids typos affecting choice of method)
=> Make diagonalisation clear default method

src/blip_minimisation.module.f90, src/initial_read_module.f90, src/initialisation_module.f90, src/move_atoms.module.f90, src/store_matrix_module.f90
Main change is to fix the crash on saving SF coefficients (which aren't defined for blips) but also to allow loading of blip coefficients at job start and small tweaks to blip minimisation
=> Updates for blips as a basis

src/calc_matrix_elements_module.f90
Change GEMM call in get_matrix_elements (transpose) so that access to acc_block is contiguous within innermost loop, and replace inner loop with array segment.
=> Implement contiguous access to acc_block in get_matrix_elements

src/initial_read_module.f90
I have made the LFD range equal to the MSSF range by default, and also added a warning if LFD range is less than MSSF range
=> Improve LFD range input

testsuite/README.md, testsuite/test_check_output.py
Closes #200
Each Fortran test now has its own parametrized python test that specifies the values it checks from the output. I would have liked to also make `results` a fixture, but I couldn't figure out how to pass the path into a fixture.
=> Refactor the testsuite

src/force_module.f90, src/move_atoms.module.f90
There was a missing minus sign in the PCC part of the non-SCF forces, and a missing non-SCF exception when rebuilding the charge density from the DM after atomic movement.
With this change, non-SCF forces are correct, and non-SCF stress is correct for the non-neutral-atom case (another fix is needed for that!).
Fixes #118
=> Fixed problems with non-SCF forces and structural optimisation

src/DiagModule.f90, src/ScalapackFormat.f90
I have not checked many examples, but I would like to create a pull request to the branch (proj_PadHamiltonianMatrix). 
For my test systems, I have confirmed that this version correctly runs with a given block size provided in Conquest_input.
I think this version should be already very useful, since it should improve the efficiency of CONQUEST dramatically in some cases. (especially when the size of Hamiltonian or Overlap matrix is a prime number)
At present, I assume that users will provide the block size by theirselves. 
1. I have not considered the case for the small size of matrix.   (when block size ~ matrix size)
2. I have not checked whether the code works for multiple k-points, with `Diag.KProcGroups` more than 1.
3. I have not followed how (# of proc rows) and (# of proc cols) …
=> Pull request to proj_PadHamiltonianMatrix (should work with a given block size)

docs/input_tags.rst, src/XC_CQ_module.f90, src/XC_LibXC_v4_module.f90, src/XC_LibXC_v5_module.f90, src/force_module.f90, src/initial_read_module.f90
This fixes issues in stress calculations for non-SCF calculations and calculations where the neutral atom (NA) potential is *not* used.
Note that for non-SCF calculations with GGA there is an approximation relating to the stress that comes from the change of XC energy with gradient of the charge density.  Strictly speaking, this should be calculated from a mixture of input and output densities, but the resulting formulae and code will be very complicated.  For now, we take a mixture of the stress calculated with input density and the stress calculated with output density; this approximation is accurate to better than 0.1GPa in all tests, and is certainly better than the existing calculation using just input density.
=> Fix non-NA and non-SCF stress issues

src/DMMinModule.f90, src/SelfCon_module.f90, src/pao_minimisation.module.f90
It may not be a bug, but ..
after I updated the MacOS, I encountered a problem in the following part with the option (-O3).
if (n_dumpL>0 .and. mod (n_iter, n_dumpL) == 0) then 
call dump_pos_and_matrices(index=unit_DM_save)
endif
The problem seems to come from the 2nd one when n_dumpL=0. I thought it is not used since we also checked n_dumpL. But, it is probably safer to change it to
if (n_dumpL>0) then
if(mod (n_iter, n_dumpL) == 0) call dump_pos_and_matrices(index=unit_DM_save) 
endif
=> Bug(?) in the if-statement before calling dump_pos_and_matrices

tools/PostProcessing/stm_module.f90
"fermi_offset" can be read as 'STM.FermiOffset' in Conquest_input
but was never used in the code.
The code has been modified to add fermi_offset to Emin and Emax in stm_module.f90.
This branch is related to issue #208 .
=> PP: Add Fermi_offset

tools/PostProcessing/read_module.f90
In Conquest_out of PostProcessing, Efermi is written only in Hartree unit,
while the energy range of STM is written in eV.
So for easy comparison with the energy range, Efermi in eV unit has been added in Conquest_out.
This is related to issue #209 .
=> PP: Added output of Efermi in eV unit

src/PAO_grid_transform_module.f90
The threading implementation in PAO_grid_transform_module currently in `tk-thread-calc-matrix` has a lot of OpenMP overheads, as the vtune analysis below shows. This PR is an attempt to thread the loop over blocks as we originally envisioned, by moving the calculation of offsets to `griddata` into a separate loop. It significantly improves the performance of the threaded region starting around 10s:
to
I'd recommend using this as a starting point for implementing #244
=> Improve threading in PAO_grid_transform_module

src/io_module.f90, tools/PostProcessing/read_module.f90
Add extra digits to k-point weight and number of k-point formatting in Conquest output.  Also ensure that projected DOS checks for limited energy window output from Conquest (read the appropriate flag)
=> Fix issues with eigenvalue output format

src/PAO_grid_transform_module.f90, src/S_matrix_module.f90, src/exx_evalpao.f90, src/force_module.f90, src/multisiteSF_module.f90, src/ol_ang_coeff_subs.f90, src/system.make, src/test_force_module.f90
Closes #244 
I've merged the two identical subroutines into `PAO_or_gradPAO_to_grid`. The subroutine called in the inner loop is passed in as a procedure argument through an interface. As a side effect I had to always pass `direction` into both subroutines to make them conform to the same interface, in `evaluate_pao` it's just a dummy argument that does nothing. I've updated all calls to `PAO_or_gradPAO_to_grid`, `evaluate_pao` and `pao_elem_derivative_2` and added a bit of explanation in comments.
Very open to a more descriptive names for the subroutine and the interface
Gets rid of OpenMP overheads in `single_PAO_to_grad` we were seeing earlier
=> Combine single_PAO_to_grid and single_PAO_to_grad

src/multiply_kernel_default.f90, src/multiply_kernel_gemm.f90, src/multiply_kernel_ompDoii.f90, src/multiply_kernel_ompDoik.f90, src/multiply_kernel_ompDojk.f90, src/multiply_kernel_ompGemm.f90, src/multiply_kernel_ompGemm_m.f90, src/multiply_module.f90
=> Optimise threading in ompGemm multiply kernel

benchmarks/matrix_multiply/Conquest_input, benchmarks/water_64mols/Conquest_input
Minor fix: I'd like all benchmarks to have the same target for their output to make automation simpler. It's easier to deal with stdout than the `Conquest_out` file.
=> Fix all benchmarks to output to stdout

src/matrix_module.f90, src/multiply_kernel_default.f90, src/multiply_kernel_gemm.f90, src/multiply_kernel_ompDoii.f90, src/multiply_kernel_ompDoik.f90, src/multiply_kernel_ompDoji.f90, src/multiply_kernel_ompDojk.f90, src/multiply_kernel_ompGemm.f90, src/multiply_kernel_ompGemm_m.f90, src/multiply_module.f90
Closes #280 
Uses assumed shape arrays for remote index arrays. These can vary in size and using a fixed size leads to accessing uninitialized memory.
Edit: I wanted to clarify that the inputs you gave in #292 still fail for me on all multiply kernels. So I'm not claiming to fix *that* issue. But I discovered a different issue and I'm fixing it :grinning: 
Edit2: The reason the inputs from #292 fail for me is that my machine runs out of memory. Based on our last discussion that is to be expected with the size of the problem.
=> Fix multiply kernel memory leak

src/initial_read_module.f90, src/multiply_kernel_default.f90, src/multiply_kernel_gemm.f90, src/multiply_kernel_ompDoii.f90, src/multiply_kernel_ompDoik.f90, src/multiply_kernel_ompDoji.f90, src/multiply_kernel_ompDojk.f90, src/multiply_kernel_ompGemm.f90, src/multiply_kernel_ompGemm_m.f90, src/multiply_kernel_ompTsk.f90
This enables us to see which matrix multiplication kernel is being used; given that the code changes with kernel, I think that this record is important.
=> Add ID strings to matrix multiplication kernels and write out

src/Makefile
This seems to fix a strange issue with GCC13 on Mac
=> Compile pseudo_tm_info.f90 without optimisation

src/Makefile
While trying to compile without the mpi compiler wrapper, I noticed that the order of linker flags in the Makefile seems incorrect. According to [this stackoverflow thread](https://stackoverflow.com/questions/35897290/what-is-the-right-order-of-linker-flags-in-gcc) the reverse order used to work but ceased a while ago.With the order of flags in current `develop`, I would fail to link the MPI library with `gfortran-13` after adding the flags given by `mpifort --showme:link` to `LINKFLAGS` in my `system.make`. Changing to the correct the order fixed my issue.
=> Fix order of flags in Makefile

.readthedocs.yml, docs/groundstate.rst, docs/input_tags.rst, docs/installing.rst
Fix a problem with readthedocs setup, add information on restarting SCF from existing DM or charge density and fix formatting in Spack installation text.
=> Updates to fix RTD and add information on restarting

.github/workflows/makefile.yml
This updates the `checkout` and `setup-python` actions used in the CI workflow to their latest released versions. Silences the warnings in the github actions output.
=> Update versions of github actions

src/mult_module.f90
Sub: end_ops was not called for SXrange and Xrange so mat for those ranges are not deallocated,
which causes a problem when atomic positions are moved and mat is updated by calling matrix_ini.
Now "call end_ops" were added for SXrange and Xrange in sub:fmmi.
This is related to issue #355.
=> Adding end_ops for SXrange and Xrange in subroutine:fmmi

src/mult_module.f90
sf was corrected to sf1 for loc to check overflow.
This is related to issue #353.
=> Bug fix: in sub: matrix_trace in mult_module.f90 (issue #353)

src/matrix_comms_module.f90, src/multiply_module.f90
This PR removes pointers to `part_array` in `multiply_module` and passes slices of `part_array` to subroutines instead. It also tries to clarify the indexing of `part_array` to make it clearer which slice is being passed.
I'm open to opinions on whether or not this is a good idea. It's more of a style change than anything else, although it should make the code more robust against the kind of memory errors in #280. I would argue this is a more Fortran style use of arrays, compared to the C-style use of pointers. It does make the subroutine calls somewhat longer
=> Remove pointers in multiply module

docs/installing.rst
I added a brief description of the OpenMP runtime scheduling into the documentation, based on our discussion today.
=> Document OpenMP scheduling

src/exx_kernel_default.f90
We actually build matXatomf so change this throughout EXX. Intermittent bug due to pointer assignment fixed.
=> Change matX to matXatomf and fix bug

docs/convergence.rst, docs/groundstate.rst, docs/input-output.rst, docs/input_tags.rst, src/initial_read_module.f90
Added parameters to allow user to set the spacing for the integration grid and the Brillouin zone integration grid rather than number of points or energy.  Added documentation.
=> Specify integration grid spacing and k-point grid spacing

src/pseudo_tm_info.f90
The update to ion files to include information on the type of pseudopotential (ONCV or HGH) was not taken into account in the pseudopotential reading code; this fixes the bug.
=> Made pseudopotential read compatible with new code

src/ScalapackFormat.f90, src/initial_read_module.f90
Dave reported that CONQUEST stops when Diag.PaddingHmatrix is true for small systems with multiple processes. (Thank you! > Dave) I have changed the code to set "Diag.PaddingHmatrix" as false in such cases.
I also moved the checking part into "initial_read".
=> Removed a bug 

src/initial_read_module.f90
The atomic spin was being read without testing for an overall spin polarised calculation, leading to the initial atomic spin flag being set and a crash.  Now fixed.
=> Initial atomic spin only set for spin polarised calculations

src/initial_read_module.f90
Constraints are not applied in this case (OptCellMethod 3); warning now printed
=> Warn user if optimising cell and ions with cell constraints

docs/input_tags.rst
Updated a part of the manual related to  "Diag.BlockSizeR" to explain the change of the default value of BlockSizeR.
=> changed the part "Diag.BlockSizeR" in manual

docs/input_tags.rst
changed the default value of BlockSizeR from 30 to 32
=> changed the default value of BlockSizeR from 30 to 32
